#!/bin/bash
raport_creator="Wojciech Jarczak"
raport_name="System performance"

DATABASENAME="raports"
DATABASEUSER="wjarczak"
DATABASEPASS="P@ssw0rd"
STARTBASH=`date`

echo "*********************"
echo "Raport: $raport_name - Generated by: $raport_creator"
echo "Date: $STARTBASH"
echo "Raport saved in: $PWD"
echo ""
echo "Raport will be saved in db:$DATABASENAME"
echo "User credentials $DATABASEUSER:$DATABASEPASS"
echo "*********************"